/**
 * data/facts.json から揮発する情報のページを生成する。
 *
 * - docs/_generated/facts.md
 * - docs/_generated/last-verified.md
 * - README.md の <!-- facts:start --> 〜 <!-- facts:end --> の間
 *
 *   npm run facts            # 生成
 *   npm run facts -- --check # 生成物が最新か確認するだけ（CI 用）
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";
import { costUSD, formatUSD, sumUsage } from "../src/lib/cost.js";
import { type Facts, facts } from "../src/lib/facts.js";
import { FIXTURES_DIR, type Fixture, ROOT } from "../src/lib/fixtures.js";
import { runMain } from "../src/lib/print.js";

const HEADER = "> 自動生成（`npm run facts`）。手で編集せず、`data/facts.json` を直してください。";
const fmt = (n: number) => n.toLocaleString("en-US");

export function renderFactsMd(f: Facts): string {
  return `# 変わりうる事実

${HEADER}

最終確認日: **${f.lastVerified}**

本文にはこれらの値を直接書きません。数字が必要なときはこのページにリンクします。
公式は「需要が非常に大きく、レート制限は予告なく変わりうる」としているため、特にレート制限は必ず公式で確認してください。

## モデル

| 項目 | 値 |
|---|---|
| 教材で固定しているバージョン | \`${f.model.pinned}\` |
| エイリアス | ${f.model.aliases.map((a) => `\`${a}\``).join(", ")} |

> 一次情報: https://docs.typesafe.ai/models

## 料金

| 項目 | 値 |
|---|---|
| 入力（100万トークンあたり） | $${f.pricing.inputPerMtok} |
| 出力（100万トークンあたり） | $${f.pricing.outputPerMtok} |
| 新規登録時のクレジット | ${f.signup.startingCredit} |
| ウェイトリスト | ${f.signup.waitlist ? "あり" : "なし"} |

> 一次情報: https://docs.typesafe.ai/models

## レート制限

| 項目 | 値 |
|---|---|
| トークン／秒 | ${fmt(f.rateLimits.tokensPerSecond)} |
| リクエスト／分 | ${fmt(f.rateLimits.requestsPerMinute)} |

> 一次情報: https://docs.typesafe.ai/models

## コンテキスト長

| 項目 | 値 |
|---|---|
| 合計 | ${fmt(f.context.totalTokens)} トークン |
| state ＋ 最長の質問 | ${fmt(f.context.statePlusLongestQuestion)} トークン |

> 一次情報: https://docs.typesafe.ai/models

## API と SDK

| 項目 | 値 |
|---|---|
| エンドポイント | \`${f.endpoint}\` |
| JavaScript SDK | \`${f.sdk.js}\` ${f.sdk.jsVersion} |
| Python SDK | \`${f.sdk.python}\` |

> 一次情報: https://docs.typesafe.ai/sdk/javascript
`;
}

export function renderLastVerifiedMd(f: Facts, docMapCheckedAt: string | null): string {
  return `# 最終確認日

${HEADER}

| 対象 | 最終確認日 | 確認方法 |
|---|---|---|
| data/facts.json（モデル・料金・レート制限など） | ${f.lastVerified} | 手動確認＋ \`npm run facts:verify\` |
| 公式ドキュメント一覧（llms.txt） | ${docMapCheckedAt ?? "未実施"} | \`npm run docmap\`（週次CI） |
`;
}

/** 費用の目安に付ける注記。見本データ（合成）がどのくらい混ざっているかで文面を変える */
export function syntheticNote(share: number, lang: "ja" | "en"): string {
  if (share === 0) return "";
  if (share === 1)
    return lang === "ja"
      ? "。※ 見本データ（合成）のトークン数からの推定"
      : ". Estimated from the token counts of the sample (synthetic) data";
  return lang === "ja"
    ? "。※ 一部は見本データ（合成）のトークン数からの推定"
    : ". Partly estimated from the token counts of the sample (synthetic) data";
}

/** lang のサンプルのリクエストを1回ずつ送ったときのトークン数。英語モードの fixture は fixtures/en/ にある */
export function estimateFullRun(lang: "ja" | "en" = "ja"): {
  inputTokens: number;
  costUSD: number;
  /** 合成データの割合。0 なら全部実測、1 なら全部見本 */
  syntheticShare: number;
} {
  const fixtures = readdirSync(FIXTURES_DIR, { recursive: true })
    .map(String)
    // errors は見本のエラー、*-claude は Anthropic の応答なので Jev の費用に含めない
    .filter(
      (f) =>
        f.endsWith(".json") &&
        !f.startsWith("errors") &&
        !/-claude\//.test(f) &&
        (lang === "en" ? f.startsWith("en/") : !f.startsWith("en/")),
    )
    .map((f) => JSON.parse(readFileSync(join(FIXTURES_DIR, f), "utf8")) as Fixture);
  const usage = sumUsage(
    ...fixtures.map(
      (fx) =>
        (fx.response.body as { usage?: { input_tokens: number; output_tokens: number } }).usage ?? {
          input_tokens: 0,
          output_tokens: 0,
        },
    ),
  );
  return {
    inputTokens: usage.input_tokens,
    costUSD: costUSD(usage),
    syntheticShare:
      fixtures.length === 0
        ? 0
        : fixtures.filter((fx) => fx.meta.source === "synthetic").length / fixtures.length,
  };
}

export function renderReadmeBlock(f: Facts, docMapCheckedAt: string | null): string {
  const est = estimateFullRun();
  return [
    "<!-- facts:start -->",
    "```",
    `最終検証: ${f.lastVerified} ｜ 対象モデル: ${f.model.pinned} ｜ SDK: ${f.sdk.js} ${f.sdk.jsVersion}`,
    `公式ドキュメント差分チェック: ${docMapCheckedAt ?? "未実施"}`,
    "```",
    "",
    `全サンプルのリクエストを1回ずつ live で送ったときの Jev の費用の目安: 約 ${formatUSD(est.costUSD)}（入力 ${est.inputTokens.toLocaleString("en-US")} トークン、新規クレジット ${f.signup.startingCredit} の ${((est.costUSD / Number(f.signup.startingCredit.replace(/[^\d.]/g, ""))) * 100).toPrecision(2)}%）${syntheticNote(est.syntheticShare, "ja")}。応用B の Claude の費用は別にかかります`,
    "<!-- facts:end -->",
  ].join("\n");
}

const HEADER_EN =
  "> Generated by `npm run facts`. Do not edit by hand; edit `data/facts.json` instead.";

export function renderFactsMdEn(f: Facts): string {
  return `# Facts that change

${HEADER_EN}

Last verified: **${f.lastVerified}**

The chapters never state these values directly. When a number is needed, they link to this page.
The official docs say demand is very high and rate limits may change without notice, so always check rate limits in the official docs.

## Model

| Item | Value |
|---|---|
| Version pinned by this course | \`${f.model.pinned}\` |
| Aliases | ${f.model.aliases.map((a) => `\`${a}\``).join(", ")} |

> Primary source: https://docs.typesafe.ai/models

## Pricing

| Item | Value |
|---|---|
| Input (per million tokens) | $${f.pricing.inputPerMtok} |
| Output (per million tokens) | $${f.pricing.outputPerMtok} |
| Credit on sign-up | ${f.signup.startingCredit} |
| Waitlist | ${f.signup.waitlist ? "yes" : "no"} |

> Primary source: https://docs.typesafe.ai/models

## Rate limits

| Item | Value |
|---|---|
| Tokens per second | ${fmt(f.rateLimits.tokensPerSecond)} |
| Requests per minute | ${fmt(f.rateLimits.requestsPerMinute)} |

> Primary source: https://docs.typesafe.ai/models

## Context length

| Item | Value |
|---|---|
| Total | ${fmt(f.context.totalTokens)} tokens |
| State + longest question | ${fmt(f.context.statePlusLongestQuestion)} tokens |

> Primary source: https://docs.typesafe.ai/models

## API and SDK

| Item | Value |
|---|---|
| Endpoint | \`${f.endpoint}\` |
| JavaScript SDK | \`${f.sdk.js}\` ${f.sdk.jsVersion} |
| Python SDK | \`${f.sdk.python}\` |

> Primary source: https://docs.typesafe.ai/sdk/javascript
`;
}

export function renderReadmeBlockEn(f: Facts, docMapCheckedAt: string | null): string {
  const est = estimateFullRun("en");
  const credit = Number(f.signup.startingCredit.replace(/[^\d.]/g, ""));
  return [
    "<!-- facts:start -->",
    "```",
    `Last verified: ${f.lastVerified} | Model: ${f.model.pinned} | SDK: ${f.sdk.js} ${f.sdk.jsVersion}`,
    `Official docs diff check: ${docMapCheckedAt ?? "not run yet"}`,
    "```",
    "",
    `Estimated Jev cost of sending every English sample request once in live mode: about ${formatUSD(est.costUSD)} (${est.inputTokens.toLocaleString("en-US")} input tokens, ${((est.costUSD / credit) * 100).toPrecision(2)}% of the ${f.signup.startingCredit} sign-up credit)${syntheticNote(est.syntheticShare, "en")}. Claude usage in Advanced B is billed separately`,
    "<!-- facts:end -->",
  ].join("\n");
}

const BLOCK = /<!-- facts:start -->[\s\S]*?<!-- facts:end -->/;

function docMapCheckedAt(): string | null {
  const file = join(ROOT, "data", "doc-map.json");
  if (!existsSync(file)) return null;
  return (JSON.parse(readFileSync(file, "utf8")) as { checkedAt: string | null }).checkedAt;
}

async function main() {
  const check = process.argv.includes("--check");
  const checkedAt = docMapCheckedAt();
  const readmePath = join(ROOT, "README.md");
  const readme = readFileSync(readmePath, "utf8");
  if (!BLOCK.test(readme))
    throw new Error("README.md に <!-- facts:start --> 〜 <!-- facts:end --> がありません");

  const readmeEnPath = join(ROOT, "README.en.md");
  const readmeEn = readFileSync(readmeEnPath, "utf8");
  if (!BLOCK.test(readmeEn))
    throw new Error("README.en.md has no <!-- facts:start --> ... <!-- facts:end --> block");

  const outputs: [string, string][] = [
    [join(ROOT, "docs", "_generated", "facts.md"), renderFactsMd(facts)],
    [join(ROOT, "docs", "_generated", "last-verified.md"), renderLastVerifiedMd(facts, checkedAt)],
    [readmePath, readme.replace(BLOCK, renderReadmeBlock(facts, checkedAt))],
    [join(ROOT, "docs", "_generated", "facts.en.md"), renderFactsMdEn(facts)],
    [readmeEnPath, readmeEn.replace(BLOCK, renderReadmeBlockEn(facts, checkedAt))],
  ];

  const stale = outputs.filter(
    ([file, content]) => !existsSync(file) || readFileSync(file, "utf8") !== content,
  );
  if (check) {
    if (stale.length > 0) {
      console.error(
        `生成物が古くなっています。npm run facts を実行してください:\n${stale.map(([f]) => `  - ${relative(ROOT, f)}`).join("\n")}`,
      );
      process.exitCode = 1;
    }
    return;
  }
  for (const [file, content] of stale) writeFileSync(file, content);
  console.log(
    stale.length === 0 ? "変更なし" : `更新: ${stale.map(([f]) => relative(ROOT, f)).join(", ")}`,
  );
}

runMain(import.meta.url, main);
